print("Wie ben jij?")
naam = input()
print("fijn om kennis te maken, " + naam)
print("hoe ben oud je?")
lt = input()
print("wauw je bent "+lt +" jaar oud! ik dacht dat u jogner was.")
print("waar kom jij vandaan? ")
location = input()
print(location +" huh? heb er nog nooit van gehoord hoe is het daar?")
        