import turtle

turtle.speed(0)
turtle.bgcolor("black")
turtle.pencolor("Blue")
turtle.fillcolor("white")
turtle.begin_fill()
for x in range(4):
    turtle.forward(90)
    turtle.right(3)
    turtle.forward(190)
    turtle.right(40)
    turtle.forward(50)
    turtle.left(28)
    turtle.forward(130)
    turtle.right(60)
    turtle.forward(100)
    turtle.right(80)
    turtle.forward(200)
    turtle.right(20)
    turtle.forward(300)
    turtle.left(20)
    turtle.forward(100)
    turtle.right(40)
    turtle.forward(400)
turtle.done()
